/* =====================================================================
   BANK SOAL PREDIKSI OSN-P IPA SD (TINGKAT PROVINSI) — VERSI HOTS
   Setiap soal menyajikan STIMULUS (skenario/ data pengamatan) dan
   VISUAL yang harus dianalisis (tabel data, grafik, infografis, atau
   diagram), menuntut penalaran bertingkat: menafsirkan data, menarik
   kesimpulan ilmiah, dan menerapkan konsep pada konteks baru.
   10 Paket x 20 soal isian singkat.
   Komposisi tiap paket:
     - Ranah : Biologi 8, Fisika 8, IPBA (Bumi & Antariksa) 4.
     - Kesulitan : 5 Mudah (x1), 10 Sedang (x1,25), 5 Sulit (x1,5).
       Nilai maksimal per paket = 25.
   Field "gambar" dirender mesin ilustrasi di index.html:
     table | bar | line | picto | pie | story | lever | incline |
     foodweb   (atau string SVG mentah).
   Catatan jawaban:
     - "kunci" boleh berisi beberapa alternatif dipisah "|".
     - Penilaian toleran huruf besar/kecil, spasi, tanda baca, dan
       variasi format angka (titik ribuan / koma desimal).
     - SOAL TIDAK MEMUAT CLUE cara menjawab; metode hanya di "pembahasan".
   ===================================================================== */
window.BOBOT = { mudah: 1, sedang: 1.25, sulit: 1.5 };
window.JUMLAH_PER_LEVEL = { mudah: 5, sedang: 10, sulit: 5 };

window.DATA_PAKET = [

/* ========================= PAKET 1 ========================= */
{ id:1, nama:"Paket 1", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel ciri empat hewan berikut. Hewan yang berkembang biak dengan cara melahirkan dan menyusui anaknya (kelompok mamalia) ditunjukkan oleh hewan ....",
  gambar:{t:"table",caption:"Hasil pengamatan ciri hewan",head:["Hewan","Penutup tubuh","Alat napas","Berkembang biak"],rows:[["P","Bulu","Paru-paru","Bertelur"],["Q","Sisik","Insang","Bertelur"],["R","Rambut","Paru-paru","Melahirkan"],["S","Kulit lembap","Paru-paru & kulit","Bertelur"]]},
  kunci:"R", pembahasan:"Mamalia berciri berambut, bernapas dengan paru-paru, dan melahirkan serta menyusui → hewan R."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Dua hewan memiliki daur hidup berbeda. Hewan A: telur → larva → pupa → dewasa. Hewan B: telur → nimfa → dewasa. Hewan yang mengalami metamorfosis sempurna (melalui tahap pupa/kepompong) adalah hewan ....",
  gambar:{t:"story",emoji:"🐛",text:"A: telur → larva → pupa → dewasa.   B: telur → nimfa → dewasa."},
  kunci:"A", pembahasan:"Metamorfosis sempurna melewati tahap pupa (kepompong); itu terjadi pada hewan A."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Tanaman air Hydrilla disinari lampu pada jarak berbeda, lalu jumlah gelembung gas yang muncul tiap 5 menit dicatat. Variabel yang sengaja diubah-ubah (variabel bebas) dalam percobaan ini adalah ....",
  gambar:{t:"table",caption:"Pengaruh jarak lampu terhadap gelembung gas",head:["Jarak lampu (cm)","Gelembung / 5 menit"],rows:[["10","60"],["20","32"],["30","15"],["40","7"]]},
  kunci:"jarak lampu|jarak sumber cahaya|intensitas cahaya|jarak cahaya", pembahasan:"Yang sengaja diubah peneliti adalah jarak lampu (intensitas cahaya); jumlah gelembung adalah hasil yang diamati."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan jaring-jaring makanan berikut. Banyaknya rantai makanan yang berakhir pada elang adalah ....",
  gambar:{t:"foodweb",nodes:[{id:"padi",label:"Padi",x:0.1,y:0.5},{id:"belalang",label:"Belalang",x:0.38,y:0.18},{id:"tikus",label:"Tikus",x:0.38,y:0.82},{id:"katak",label:"Katak",x:0.66,y:0.16},{id:"ular",label:"Ular",x:0.72,y:0.55},{id:"elang",label:"Elang",x:0.93,y:0.34}],links:[["padi","belalang"],["padi","tikus"],["belalang","katak"],["tikus","ular"],["katak","ular"],["tikus","elang"],["ular","elang"]]},
  kunci:"3", pembahasan:"Rantai ke elang: (1) padi→tikus→ular→elang, (2) padi→tikus→elang, (3) padi→belalang→katak→ular→elang → 3 rantai."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Tiga bahan makanan diuji dengan reagen. Lugol menandai amilum (biru kehitaman), Biuret menandai protein (ungu), dan Benedict menandai gula (merah bata). Bahan makanan yang mengandung protein adalah ....",
  gambar:{t:"table",caption:"Hasil uji bahan makanan",head:["Bahan","+ Lugol","+ Biuret","+ Benedict"],rows:[["Putih telur","tetap","ungu","tetap"],["Nasi","biru kehitaman","tetap","tetap"],["Pisang","tetap","tetap","merah bata"]]},
  kunci:"putih telur", pembahasan:"Reagen Biuret berubah ungu hanya pada putih telur → putih telur mengandung protein."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Denyut nadi tiga siswa diukur sebelum dan sesudah berlari (lihat tabel). Peningkatan denyut nadi setelah berolahraga bertujuan mempercepat peredaran darah agar pengangkutan ... ke otot lebih cepat.",
  gambar:{t:"table",caption:"Denyut nadi (per menit)",head:["Siswa","Sebelum","Sesudah lari"],rows:[["Andi","78","124"],["Bila","80","130"],["Cinta","76","120"]]},
  kunci:"oksigen|oksigen dan sari makanan|o2", pembahasan:"Otot yang bekerja keras butuh lebih banyak oksigen; jantung memompa lebih cepat sehingga denyut nadi naik."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Seorang pemulia menyilangkan dua tanaman bunga merah yang sama-sama bergenotipe Mm (merah dominan terhadap putih). Dari 240 biji yang tumbuh, jumlah tanaman yang diperkirakan berbunga putih adalah ... tanaman.",
  kunci:"60", pembahasan:"Mm × Mm → merah : putih = 3 : 1. Putih = 1/4 × 240 = 60 tanaman."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Empat tanaman pacar air diberi perlakuan berbeda, lalu penurunan tinggi air dalam wadahnya diukur selama 1 jam. Berdasarkan data, faktor yang paling mempercepat penguapan air (transpirasi) adalah ....",
  gambar:{t:"table",caption:"Penurunan air dalam 1 jam",head:["Perlakuan","Penurunan air (mL)"],rows:[["Di tempat teduh","4"],["Diberi kipas angin","9"],["Sebagian daun dipotong","2"],["Tanpa angin, terkena panas","6"]]},
  kunci:"angin|kipas|kipas angin|hembusan angin|adanya angin", pembahasan:"Penurunan air terbesar (9 mL) terjadi saat diberi kipas → angin mempercepat transpirasi."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Grafik berikut menunjukkan jarak terhadap waktu sebuah mobil mainan. Kecepatan mobil tersebut adalah ... m/s.",
  gambar:{t:"line",title:"Jarak (m) terhadap waktu (s)",labels:["0","1","2","3","4"],values:[0,15,30,45,60]},
  kunci:"15", pembahasan:"Grafik lurus (GLB). Kecepatan = kemiringan = 60 m ÷ 4 s = 15 m/s."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan data kecepatan sebuah benda tiap 2 detik. Berdasarkan polanya, jenis gerak benda tersebut adalah ....",
  gambar:{t:"table",caption:"Kecepatan benda",head:["Waktu (s)","Kecepatan (m/s)"],rows:[["0","0"],["2","4"],["4","8"],["6","12"]]},
  kunci:"GLBB|gerak lurus berubah beraturan|dipercepat beraturan", pembahasan:"Kecepatan bertambah tetap 4 m/s tiap 2 s → gerak lurus berubah beraturan (GLBB) dipercepat."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Perhatikan tuas pada gambar. Agar tuas seimbang, besar gaya kuasa (F) yang diperlukan untuk mengangkat beban tersebut adalah ... N.",
  gambar:{t:"lever",beban:600,lb:30,lk:120,unit:"cm"},
  kunci:"150", pembahasan:"F × lengan kuasa = beban × lengan beban → F = (600 × 30) ÷ 120 = 150 N."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Sebuah peti didorong naik melalui bidang miring seperti gambar. Jika berat peti 900 N, gaya minimal untuk mendorong peti di sepanjang bidang miring adalah ... N.",
  gambar:{t:"incline",panjang:5,tinggi:1.5,unit:"m"},
  kunci:"270", pembahasan:"F = (berat × tinggi) ÷ panjang = (900 × 1,5) ÷ 5 = 270 N."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Grafik menunjukkan suhu suatu zat cair yang dipanaskan terus-menerus. Berdasarkan grafik, zat tersebut mendidih (suhu tetap walau dipanaskan) pada suhu ... °C.",
  gambar:{t:"line",title:"Suhu (°C) terhadap waktu (menit)",labels:["0","2","4","6","8","10"],values:[20,50,80,100,100,100]},
  kunci:"100", pembahasan:"Setelah menit ke-6 suhu tetap di 100°C meski dipanaskan → titik didih zat = 100°C."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Hasil pengukuran pada sebuah lampu ditunjukkan pada tabel. Berdasarkan data, besar hambatan lampu tersebut adalah ... Ω.",
  gambar:{t:"table",caption:"Hasil pengukuran",head:["Besaran","Nilai"],rows:[["Tegangan","6 V"],["Kuat arus","2 A"]]},
  kunci:"3", pembahasan:"R = V ÷ I = 6 ÷ 2 = 3 Ω."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Data tekanan hidrostatis pada beberapa kedalaman air ditunjukkan grafik berikut. Berdasarkan pola data, tekanan hidrostatis pada kedalaman 6 m adalah ... Pa.",
  gambar:{t:"line",title:"Tekanan (Pa) terhadap kedalaman (m)",labels:["1","2","3","4"],values:[10000,20000,30000,40000]},
  kunci:"60000", pembahasan:"Tekanan bertambah 10.000 Pa tiap 1 m. Pada 6 m → 6 × 10.000 = 60.000 Pa."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Dua wadah air dengan suhu berbeda dicampur (lihat tabel). Bila tidak ada kalor yang hilang ke lingkungan, suhu campuran setelah setimbang adalah ... °C.",
  gambar:{t:"table",caption:"Dua wadah air dicampur",head:["Air","Massa","Suhu"],rows:[["A","200 g","90 °C"],["B","300 g","20 °C"]]},
  kunci:"48", pembahasan:"Suhu campuran = (200×90 + 300×20) ÷ (200+300) = 24.000 ÷ 500 = 48 °C."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel jarak beberapa planet dari Matahari. Planet yang letaknya paling dekat dengan Matahari adalah ....",
  gambar:{t:"table",caption:"Jarak rata-rata dari Matahari",head:["Planet","Jarak (juta km)"],rows:[["Bumi","150"],["Merkurius","58"],["Mars","228"],["Venus","108"]]},
  kunci:"merkurius", pembahasan:"Jarak terkecil (58 juta km) dimiliki Merkurius → planet terdekat dengan Matahari."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Grafik berikut menampilkan rata-rata curah hujan bulanan suatu daerah. Berdasarkan grafik, puncak musim hujan terjadi pada bulan ....",
  gambar:{t:"bar",title:"Curah hujan (mm)",labels:["Jan","Feb","Mar","Apr","Mei","Jun"],values:[320,290,180,90,40,20]},
  kunci:"januari|jan", pembahasan:"Curah hujan tertinggi (320 mm) terjadi pada bulan Januari → puncak musim hujan."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Sebuah pesawat berangkat dari Jakarta (WIB) pukul 07.00 dan terbang selama 5 jam menuju Jayapura (WIT). Pukul berapa waktu setempat (WIT) pesawat tersebut mendarat?",
  kunci:"14.00|14:00|14|2 siang", pembahasan:"Tiba pukul 07.00 + 5 = 12.00 WIB. WIT = WIB + 2 jam → 12.00 + 2 = 14.00 WIT."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Perhatikan diagram posisi Matahari, Bulan, dan Bumi berikut. Jika bayangan Bulan jatuh dan menutupi sebagian permukaan Bumi, peristiwa yang terjadi adalah ....",
  gambar:'<svg viewBox="0 0 360 120" class="g-svg"><line x1="20" y1="60" x2="340" y2="60" stroke="#9bbcb0" stroke-dasharray="5 4"/><circle cx="50" cy="60" r="26" fill="#f59e0b"/><text x="50" y="104" class="g-lab">Matahari</text><circle cx="205" cy="60" r="9" fill="#9aa7c4"/><text x="205" y="104" class="g-lab">Bulan</text><circle cx="312" cy="60" r="18" fill="#2563eb"/><text x="312" y="104" class="g-lab">Bumi</text></svg>',
  kunci:"gerhana matahari", pembahasan:"Bulan berada di antara Matahari dan Bumi; bayangan Bulan jatuh ke Bumi → gerhana Matahari."}
]},

/* ========================= PAKET 2 ========================= */
{ id:2, nama:"Paket 2", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel ciri tiga tumbuhan. Tumbuhan yang sudah memiliki pembuluh angkut tetapi masih berkembang biak menggunakan spora adalah ....",
  gambar:{t:"table",caption:"Ciri tumbuhan",head:["Tumbuhan","Pembuluh angkut","Alat berkembang biak"],rows:[["Lumut","Tidak ada","Spora"],["Paku","Ada","Spora"],["Mangga","Ada","Biji"]]},
  kunci:"paku|tumbuhan paku", pembahasan:"Paku berpembuluh (ada xilem-floem) namun berkembang biak dengan spora → tumbuhan paku."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Tabel berikut menunjukkan bentuk paruh dan jenis makanan tiga burung. Burung yang memiliki paruh paling sesuai untuk mengoyak daging mangsa adalah ....",
  gambar:{t:"table",caption:"Bentuk paruh burung",head:["Burung","Bentuk paruh","Makanan"],rows:[["Pipit","Pendek, tebal, kuat","Biji"],["Elang","Tajam, melengkung","Daging"],["Kolibri","Panjang, runcing","Nektar"]]},
  kunci:"elang", pembahasan:"Paruh tajam dan melengkung milik elang cocok untuk mengoyak daging mangsa."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Dua kelompok biji kacang hijau ditanam di tempat terang dan gelap, lalu tingginya diukur. Berdasarkan data, tanaman yang batangnya tumbuh memanjang lebih cepat berada di tempat ....",
  gambar:{t:"table",caption:"Tinggi kecambah (cm)",head:["Hari ke-","Terang","Gelap"],rows:[["3","2","5"],["6","4","11"],["9","6","18"]]},
  kunci:"gelap", pembahasan:"Di tempat gelap kecambah lebih tinggi (etiolasi) karena hormon auksin tidak terurai oleh cahaya."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel hasil pengamatan interaksi antarorganisme (+ = untung, − = rugi, 0 = tidak terpengaruh). Interaksi yang merupakan simbiosis parasitisme adalah ....",
  gambar:{t:"table",caption:"Interaksi dua organisme",head:["Interaksi","Organisme 1","Organisme 2"],rows:[["Benalu – Mangga","+","−"],["Anggrek – Pohon","+","0"],["Lebah – Bunga","+","+"]]},
  kunci:"benalu - mangga|benalu-mangga|benalu dan mangga|benalu", pembahasan:"Parasitisme = satu untung (+), satu rugi (−) → interaksi benalu–mangga."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Tabel berikut menunjukkan beberapa organ pencernaan dan enzimnya. Organ yang menghasilkan enzim pengubah protein menjadi pepton adalah ....",
  gambar:{t:"table",caption:"Organ dan enzim pencernaan",head:["Organ","Enzim","Mengubah"],rows:[["Mulut","Ptialin","Amilum → maltosa"],["Lambung","Pepsin","Protein → pepton"],["Usus halus","Lipase","Lemak → asam lemak"]]},
  kunci:"lambung", pembahasan:"Enzim pepsin yang mengubah protein menjadi pepton dihasilkan oleh lambung."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Grafik berikut menunjukkan jumlah energi (kkal) pada tiap tingkat trofik suatu ekosistem. Berdasarkan data, energi yang berpindah dari produsen ke konsumen I hanya sekitar ... %.",
  gambar:{t:"bar",title:"Energi tiap tingkat (kkal)",labels:["Produsen","Konsumen I","Konsumen II"],values:[10000,1000,100]},
  kunci:"10", pembahasan:"Energi konsumen I ÷ produsen × 100% = 1000 ÷ 10000 × 100% = 10%."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Dua tanaman bergenotipe AaBb disilangkan (AaBb × AaBb) dengan kedua sifat dominan penuh. Dari 320 keturunan, jumlah yang diperkirakan memiliki kedua sifat dominan (A_B_) adalah ... tanaman.",
  kunci:"180", pembahasan:"Perbandingan A_B_ = 9/16. Maka 9/16 × 320 = 180 tanaman."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Hydrilla difotosintesiskan di bawah cahaya berwarna berbeda, lalu gelembung gas dihitung (lihat grafik). Cahaya yang paling efektif untuk fotosintesis adalah cahaya ....",
  gambar:{t:"bar",title:"Gelembung gas / 5 menit",labels:["Merah","Hijau","Biru","Gelap"],values:[46,10,38,0]},
  kunci:"merah", pembahasan:"Gelembung terbanyak (46) muncul pada cahaya merah → paling banyak diserap klorofil untuk fotosintesis."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Grafik jarak terhadap waktu seorang pelari ditunjukkan berikut. Kecepatan lari orang tersebut adalah ... m/s.",
  gambar:{t:"line",title:"Jarak (m) terhadap waktu (s)",labels:["0","1","2","3"],values:[0,10,20,30]},
  kunci:"10", pembahasan:"Grafik lurus, kecepatan = 30 m ÷ 3 s = 10 m/s."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Saat memasak, gagang panci logam yang ujungnya jauh dari api lama-lama ikut terasa panas walaupun tidak menyentuh api. Peristiwa ini menunjukkan perpindahan kalor secara ....",
  gambar:{t:"story",emoji:"🍳",text:"Panci logam dipanaskan di atas kompor; bagian gagang yang dipegang ikut memanas."},
  kunci:"konduksi|hantaran", pembahasan:"Kalor merambat melalui logam tanpa bagian logamnya ikut berpindah → konduksi."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Perhatikan tuas pada gambar. Besar gaya kuasa (F) yang diperlukan agar tuas seimbang adalah ... N.",
  gambar:{t:"lever",beban:800,lb:25,lk:100,unit:"cm"},
  kunci:"200", pembahasan:"F = (beban × lengan beban) ÷ lengan kuasa = (800 × 25) ÷ 100 = 200 N."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Sebuah balok menekan lantai dengan data seperti pada tabel. Tekanan yang diberikan balok pada lantai adalah ... Pa.",
  gambar:{t:"table",caption:"Data balok",head:["Besaran","Nilai"],rows:[["Gaya tekan","150 N"],["Luas alas","0,05 m²"]]},
  kunci:"3000", pembahasan:"P = F ÷ A = 150 ÷ 0,05 = 3.000 Pa."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Sebuah kapal mengirim bunyi ke dasar laut. Bunyi pantul diterima kembali 4 detik kemudian. Jika cepat rambat bunyi di air 1.500 m/s, kedalaman laut di tempat itu adalah ... m.",
  gambar:{t:"story",emoji:"🚢",text:"Bunyi dipancarkan lurus ke bawah, memantul di dasar laut, lalu kembali ke kapal dalam 4 detik."},
  kunci:"3000", pembahasan:"Bunyi menempuh dua kali kedalaman: 2d = v×t = 1500×4 = 6000 m → d = 3.000 m."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Sebuah lampu memiliki data seperti pada tabel. Daya listrik yang digunakan lampu tersebut adalah ... watt.",
  gambar:{t:"table",caption:"Data lampu",head:["Besaran","Nilai"],rows:[["Tegangan","12 V"],["Hambatan","4 Ω"]]},
  kunci:"36", pembahasan:"I = V ÷ R = 12 ÷ 4 = 3 A. Daya P = V × I = 12 × 3 = 36 watt."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Kalor sebesar 21.000 J diberikan untuk memanaskan 0,5 kg air. Bila kalor jenis air 4.200 J/kg°C, kenaikan suhu air tersebut adalah ... °C.",
  kunci:"10", pembahasan:"ΔT = Q ÷ (m × c) = 21.000 ÷ (0,5 × 4.200) = 21.000 ÷ 2.100 = 10 °C."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Sebuah pompa hidrolik memiliki data penampang seperti pada tabel. Jika pada penampang kecil diberi gaya 40 N, gaya angkat yang dihasilkan pada penampang besar adalah ... N.",
  gambar:{t:"table",caption:"Data pompa hidrolik",head:["Penampang","Luas","Gaya"],rows:[["Kecil","10 cm²","40 N"],["Besar","250 cm²","?"]]},
  kunci:"1000", pembahasan:"F₂ = F₁ × (A₂ ÷ A₁) = 40 × (250 ÷ 10) = 40 × 25 = 1.000 N."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel diameter beberapa planet. Berdasarkan data, planet terbesar dalam tata surya adalah ....",
  gambar:{t:"table",caption:"Diameter planet",head:["Planet","Diameter (km)"],rows:[["Bumi","12.742"],["Mars","6.779"],["Jupiter","139.820"],["Venus","12.104"]]},
  kunci:"jupiter|yupiter", pembahasan:"Diameter terbesar (139.820 km) dimiliki Jupiter → planet terbesar."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Grafik berikut menampilkan suhu udara suatu kota sepanjang hari. Berdasarkan grafik, suhu udara tertinggi terjadi sekitar pukul ....",
  gambar:{t:"line",title:"Suhu (°C) sepanjang hari",labels:["06","09","12","15","18"],values:[24,28,33,31,27]},
  kunci:"12|12.00|12:00|siang", pembahasan:"Nilai suhu tertinggi (33°C) ada pada pukul 12.00 (tengah hari)."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Malam ini Bulan tampak purnama. Jika satu kali siklus fase Bulan (sinodis) berlangsung sekitar 30 hari, maka bulan purnama berikutnya akan terlihat kira-kira ... hari lagi.",
  kunci:"30|29,5|29|29.5", pembahasan:"Fase Bulan berulang tiap satu periode sinodis ±29,5 hari (dibulatkan ±30 hari)."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Perhatikan diagram posisi Matahari, Bumi, dan Bulan berikut. Saat Bulan memasuki daerah bayangan inti (umbra) Bumi, peristiwa yang terjadi adalah ....",
  gambar:'<svg viewBox="0 0 360 120" class="g-svg"><line x1="20" y1="60" x2="340" y2="60" stroke="#9bbcb0" stroke-dasharray="5 4"/><circle cx="48" cy="60" r="26" fill="#f59e0b"/><text x="48" y="104" class="g-lab">Matahari</text><circle cx="205" cy="60" r="18" fill="#2563eb"/><text x="205" y="104" class="g-lab">Bumi</text><circle cx="312" cy="60" r="9" fill="#9aa7c4"/><text x="312" y="104" class="g-lab">Bulan</text></svg>',
  kunci:"gerhana bulan|gerhana bulan total", pembahasan:"Bumi berada di antara Matahari dan Bulan; Bulan masuk bayangan inti Bumi → gerhana Bulan."}
]},

/* ========================= PAKET 3 ========================= */
{ id:3, nama:"Paket 3", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan rantai makanan berikut. Organisme yang berperan sebagai konsumen tingkat II adalah ....",
  gambar:{t:"foodweb",nodes:[{id:"rumput",label:"Rumput",x:0.1,y:0.5},{id:"tikus",label:"Tikus",x:0.37,y:0.5},{id:"ular",label:"Ular",x:0.64,y:0.5},{id:"elang",label:"Elang",x:0.9,y:0.5}],links:[["rumput","tikus"],["tikus","ular"],["ular","elang"]]},
  kunci:"ular", pembahasan:"Tikus = konsumen I, ular = konsumen II, elang = konsumen III."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel ciri empat hewan vertebrata. Hewan yang termasuk kelompok reptil ditunjukkan oleh ....",
  gambar:{t:"table",caption:"Ciri hewan",head:["Hewan","Penutup tubuh","Suhu tubuh"],rows:[["Buaya","Sisik kering","Berubah-ubah"],["Ikan mas","Sisik berlendir","Berubah-ubah"],["Merpati","Bulu","Tetap"],["Sapi","Rambut","Tetap"]]},
  kunci:"buaya", pembahasan:"Reptil berciri kulit bersisik kering dan berdarah dingin (suhu berubah-ubah) → buaya."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Grafik berikut menunjukkan perubahan populasi rubah (pemangsa) dan kelinci (mangsa) selama beberapa tahun. Ketika populasi kelinci menurun tajam, beberapa waktu kemudian populasi rubah akan ....",
  gambar:{t:"line",title:"Populasi (ekor)",labels:["2018","2019","2020","2021"],values:[40,90,70,25]},
  kunci:"menurun|berkurang|turun", pembahasan:"Rubah bergantung pada kelinci sebagai makanan; bila mangsa berkurang, pemangsa kekurangan makanan sehingga populasinya menurun."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Pada uji fotosintesis (percobaan Sachs), daun direbus dalam alkohol panas sebelum ditetesi larutan iodium. Tujuan merebus daun dalam alkohol adalah untuk melarutkan ... sehingga perubahan warna pada daun mudah diamati.",
  gambar:{t:"story",emoji:"🍃",text:"Urutan: daun ditutup sebagian → dijemur → direbus air → direbus alkohol → ditetesi iodium."},
  kunci:"klorofil|zat hijau daun", pembahasan:"Alkohol melarutkan klorofil (zat hijau daun) sehingga warna biru kehitaman hasil uji amilum tampak jelas."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Tabel berikut menunjukkan frekuensi pernapasan seseorang. Peningkatan frekuensi napas saat berlari terjadi untuk memenuhi kebutuhan tubuh akan ... yang meningkat.",
  gambar:{t:"table",caption:"Frekuensi napas (per menit)",head:["Kondisi","Frekuensi"],rows:[["Istirahat","16"],["Jalan cepat","24"],["Berlari","36"]]},
  kunci:"oksigen|o2", pembahasan:"Aktivitas berat memerlukan lebih banyak oksigen untuk pembakaran, sehingga frekuensi napas meningkat."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Hewan-hewan gurun seperti pada tabel memiliki ciri khusus. Ciri 'urine sedikit dan pekat' merupakan bentuk adaptasi untuk menghemat ... di lingkungan yang kering.",
  gambar:{t:"table",caption:"Adaptasi hewan gurun",head:["Hewan","Ciri khusus"],rows:[["Unta","Punuk penyimpan lemak"],["Tikus gurun","Urine sedikit dan pekat"],["Ular gurun","Aktif pada malam hari"]]},
  kunci:"air", pembahasan:"Mengeluarkan urine sedikit dan pekat mengurangi kehilangan air → menghemat air."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Tanaman mangga berbuah manis (Mm) disilangkan dengan mangga berbuah asam (mm). Dari 160 keturunan yang dihasilkan, jumlah tanaman yang diperkirakan berbuah asam adalah ... tanaman.",
  kunci:"80", pembahasan:"Mm × mm → 1 manis (Mm) : 1 asam (mm). Asam = 1/2 × 160 = 80 tanaman."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Perhatikan jaring-jaring makanan yang dilengkapi pengurai. Jika pengurai (bakteri dan jamur pembusuk) hilang dari ekosistem, sisa makhluk hidup yang mati tidak terurai sehingga ... tanah akan berkurang.",
  gambar:{t:"foodweb",nodes:[{id:"rumput",label:"Rumput",x:0.12,y:0.4},{id:"belalang",label:"Belalang",x:0.42,y:0.22},{id:"katak",label:"Katak",x:0.7,y:0.4},{id:"pengurai",label:"Pengurai",x:0.42,y:0.82}],links:[["rumput","belalang"],["belalang","katak"],["katak","pengurai"],["rumput","pengurai"]]},
  kunci:"kesuburan|zat hara|unsur hara|kandungan hara", pembahasan:"Pengurai mengembalikan zat hara ke tanah; tanpa pengurai, kesuburan/unsur hara tanah berkurang."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Grafik kecepatan terhadap waktu sebuah benda ditunjukkan berikut. Percepatan benda tersebut adalah ... m/s².",
  gambar:{t:"line",title:"Kecepatan (m/s) terhadap waktu (s)",labels:["0","1","2","3"],values:[0,4,8,12]},
  kunci:"4", pembahasan:"Percepatan = kemiringan grafik v–t = 12 m/s ÷ 3 s = 4 m/s²."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Sebatang paku menjadi bersifat magnet setelah digosok berulang-ulang searah menggunakan sebuah magnet. Cara membuat magnet seperti ini disebut ....",
  gambar:{t:"story",emoji:"🧲",text:"Magnet digosokkan pada paku besi dengan arah yang sama dan berulang-ulang."},
  kunci:"menggosok|gosokan|digosok", pembahasan:"Membuat magnet dengan menggosokkan magnet pada benda secara searah disebut cara menggosok."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Sebuah drum dinaikkan ke truk melalui bidang miring seperti gambar. Jika berat drum 1.200 N, gaya minimal untuk mendorongnya di sepanjang bidang miring adalah ... N.",
  gambar:{t:"incline",panjang:6,tinggi:2,unit:"m"},
  kunci:"400", pembahasan:"F = (berat × tinggi) ÷ panjang = (1.200 × 2) ÷ 6 = 400 N."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Seekor penyelam berada pada kedalaman tertentu di laut (lihat data). Bila massa jenis air laut 1.000 kg/m³ dan g = 10 m/s², tekanan hidrostatis yang dialami penyelam adalah ... Pa.",
  gambar:{t:"table",caption:"Data penyelaman",head:["Besaran","Nilai"],rows:[["Kedalaman","3 m"],["Massa jenis air","1.000 kg/m³"],["Percepatan gravitasi","10 m/s²"]]},
  kunci:"30000", pembahasan:"P = ρ × g × h = 1.000 × 10 × 3 = 30.000 Pa."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Grafik suhu terhadap waktu saat es dipanaskan ditunjukkan berikut. Es melebur (suhu tetap 0°C) berlangsung dari menit ke-2 sampai menit ke- ....",
  gambar:{t:"line",title:"Suhu (°C) terhadap waktu (menit)",labels:["0","2","4","6","8"],values:[-10,0,0,0,15]},
  kunci:"6", pembahasan:"Suhu tetap 0°C (proses melebur) terjadi dari menit ke-2 hingga menit ke-6, lalu suhu naik kembali."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Sebuah lampu 20 W menyala rata-rata 10 jam setiap hari selama 30 hari. Energi listrik yang digunakan lampu tersebut adalah ... kWh.",
  kunci:"6", pembahasan:"Energi = 20 W × 10 jam × 30 hari = 6.000 Wh = 6 kWh."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Tiga hambatan disusun seperti data berikut: R1 dan R2 disusun seri, lalu hasilnya disusun paralel dengan R3. Hambatan pengganti seluruh rangkaian adalah ... Ω.",
  gambar:{t:"table",caption:"Nilai hambatan",head:["Hambatan","Nilai"],rows:[["R1","4 Ω"],["R2","4 Ω"],["R3","8 Ω"]]},
  kunci:"4", pembahasan:"R1 seri R2 = 8 Ω. Lalu 8 Ω paralel 8 Ω = (8×8)÷(8+8) = 4 Ω."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Air panas bersuhu 80°C sebanyak 100 g dicampur dengan air dingin bersuhu 20°C. Jika suhu campuran setelah setimbang 40°C, massa air dingin yang dicampurkan adalah ... gram.",
  kunci:"200", pembahasan:"Kalor lepas = kalor terima: 100×(80−40) = m×(40−20) → 4.000 = 20m → m = 200 gram."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel jenis dan proses pembentukan batuan. Batuan yang terbentuk dari pengendapan dan pemadatan material adalah ....",
  gambar:{t:"table",caption:"Jenis batuan",head:["Batuan","Proses pembentukan"],rows:[["Granit","Pembekuan magma"],["Batu pasir","Pengendapan material"],["Marmer","Perubahan suhu & tekanan"]]},
  kunci:"batu pasir|sedimen|batuan sedimen", pembahasan:"Batuan dari pengendapan material disebut batuan sedimen, contohnya batu pasir."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Grafik curah hujan suatu daerah ditunjukkan berikut. Bulan yang paling kering (musim kemarau) ditunjukkan oleh bulan ....",
  gambar:{t:"bar",title:"Curah hujan (mm)",labels:["Jun","Jul","Agu","Sep","Okt"],values:[60,30,15,45,120]},
  kunci:"agustus|agu", pembahasan:"Curah hujan terendah (15 mm) terjadi pada bulan Agustus → paling kering."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Pada suatu malam, posisi Matahari, Bumi, dan Bulan berada pada satu garis lurus dengan Bumi di tengah. Peristiwa yang dapat terjadi pada keadaan tersebut adalah ....",
  kunci:"gerhana bulan", pembahasan:"Matahari–Bumi–Bulan segaris dengan Bumi di tengah dan terjadi pada malam hari → gerhana Bulan."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Perhatikan tabel lama revolusi beberapa planet. Planet yang memerlukan waktu paling lama untuk satu kali mengelilingi Matahari adalah ....",
  gambar:{t:"table",caption:"Kala revolusi planet",head:["Planet","Kala revolusi"],rows:[["Merkurius","88 hari"],["Bumi","365 hari"],["Mars","687 hari"],["Jupiter","12 tahun"]]},
  kunci:"jupiter|yupiter", pembahasan:"Semakin jauh dari Matahari, kala revolusi makin lama. Jupiter paling jauh (12 tahun) → paling lama."}
]},

/* ========================= PAKET 4 ========================= */
{ id:4, nama:"Paket 4", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel bagian bunga dan fungsinya. Bagian bunga yang berperan sebagai alat kelamin betina adalah ....",
  gambar:{t:"table",caption:"Bagian bunga",head:["Bagian","Fungsi"],rows:[["Mahkota","Menarik serangga"],["Benang sari","Alat kelamin jantan"],["Putik","Alat kelamin betina"],["Kelopak","Melindungi kuncup"]]},
  kunci:"putik", pembahasan:"Berdasarkan tabel, alat kelamin betina pada bunga adalah putik."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Tiga hewan memiliki daur hidup seperti pada tabel. Hewan yang TIDAK mengalami tahap kepompong dalam daur hidupnya adalah ....",
  gambar:{t:"table",caption:"Daur hidup hewan",head:["Hewan","Daur hidup"],rows:[["Kupu-kupu","telur–ulat–kepompong–dewasa"],["Belalang","telur–nimfa–dewasa"],["Lalat","telur–larva–pupa–dewasa"]]},
  kunci:"belalang", pembahasan:"Belalang mengalami metamorfosis tidak sempurna (telur–nimfa–dewasa) tanpa tahap kepompong."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Tabel berikut menunjukkan tempat kerja enzim pencernaan. Jika seseorang makan nasi (karbohidrat), enzim yang pertama kali mencernanya bekerja di ....",
  gambar:{t:"table",caption:"Enzim pencernaan",head:["Tempat","Enzim","Mencerna"],rows:[["Mulut","Ptialin","Amilum"],["Lambung","Pepsin","Protein"],["Usus halus","Lipase","Lemak"]]},
  kunci:"mulut", pembahasan:"Amilum (karbohidrat) mulai dicerna oleh enzim ptialin di mulut."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan jaring-jaring makanan berikut. Jika populasi katak menurun drastis akibat diburu, populasi belalang dalam waktu dekat cenderung ....",
  gambar:{t:"foodweb",nodes:[{id:"padi",label:"Padi",x:0.12,y:0.5},{id:"belalang",label:"Belalang",x:0.42,y:0.25},{id:"tikus",label:"Tikus",x:0.42,y:0.78},{id:"katak",label:"Katak",x:0.7,y:0.3},{id:"ular",label:"Ular",x:0.9,y:0.55}],links:[["padi","belalang"],["padi","tikus"],["belalang","katak"],["katak","ular"],["tikus","ular"]]},
  kunci:"meningkat|bertambah|naik", pembahasan:"Katak adalah pemangsa belalang. Bila katak berkurang, belalang kehilangan pemangsa sehingga populasinya meningkat."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Tabel berikut menunjukkan volume urine seseorang pada kondisi berbeda. Berdasarkan data, saat seseorang banyak minum air, volume urine yang dikeluarkan menjadi lebih ....",
  gambar:{t:"table",caption:"Volume urine",head:["Kondisi","Volume urine"],rows:[["Banyak minum","Banyak, encer"],["Sedikit minum","Sedikit, pekat"],["Banyak berkeringat","Sedikit, pekat"]]},
  kunci:"banyak|banyak dan encer|banyak encer", pembahasan:"Saat banyak minum, kelebihan air dibuang melalui urine sehingga urine menjadi banyak dan encer."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Tanaman bunga pukul empat merah (MM) disilangkan dengan putih (mm) menghasilkan F1 berwarna merah muda (Mm). Jika F1 disilangkan sesamanya (Mm × Mm), perbandingan fenotipe merah : merah muda : putih pada F2 adalah ....",
  kunci:"1:2:1", pembahasan:"Pada sifat intermediet, Mm × Mm → 1 MM (merah) : 2 Mm (merah muda) : 1 mm (putih) = 1 : 2 : 1."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Perhatikan tabel produk bioteknologi dan mikroorganismenya. Produk yang dibuat dengan bantuan jamur Rhizopus oryzae adalah ....",
  gambar:{t:"table",caption:"Produk bioteknologi",head:["Produk","Mikroorganisme"],rows:[["Tempe","Rhizopus oryzae"],["Yoghurt","Lactobacillus"],["Roti","Saccharomyces"]]},
  kunci:"tempe", pembahasan:"Rhizopus oryzae adalah jamur yang dimanfaatkan dalam pembuatan tempe."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Beberapa kecambah dimasukkan ke dalam wadah tertutup yang dihubungkan dengan air kapur. Setelah beberapa jam, air kapur menjadi keruh. Hal ini membuktikan bahwa saat bernapas, kecambah menghasilkan gas ....",
  gambar:{t:"story",emoji:"🌱",text:"Kecambah dalam toples tertutup; udara dari toples dialirkan ke air kapur jernih hingga menjadi keruh."},
  kunci:"karbon dioksida|co2|karbondioksida", pembahasan:"Air kapur menjadi keruh bila bereaksi dengan karbon dioksida → respirasi menghasilkan CO₂."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan tabel pasangan besaran dan satuannya dalam SI. Besaran yang memiliki satuan kilogram adalah ....",
  gambar:{t:"table",caption:"Besaran dan satuan SI",head:["Besaran","Satuan SI"],rows:[["Panjang","meter"],["Massa","kilogram"],["Waktu","sekon"]]},
  kunci:"massa", pembahasan:"Berdasarkan tabel, besaran dengan satuan kilogram adalah massa."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Grafik jarak terhadap waktu sebuah benda ditunjukkan berikut. Antara detik ke-2 sampai detik ke-4, benda berada dalam keadaan ....",
  gambar:{t:"line",title:"Jarak (m) terhadap waktu (s)",labels:["0","1","2","3","4"],values:[0,10,20,20,20]},
  kunci:"diam|berhenti", pembahasan:"Antara detik ke-2 dan ke-4 jaraknya tetap (garis mendatar) → benda diam."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Perhatikan tuas pada gambar. Besar gaya kuasa (F) agar tuas seimbang dan dapat mengangkat beban adalah ... N.",
  gambar:{t:"lever",beban:500,lb:40,lk:100,unit:"cm"},
  kunci:"200", pembahasan:"F = (beban × lengan beban) ÷ lengan kuasa = (500 × 40) ÷ 100 = 200 N."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Sebuah bidang miring memiliki ukuran seperti gambar. Keuntungan mekanik bidang miring tersebut adalah ....",
  gambar:{t:"incline",panjang:8,tinggi:2,unit:"m"},
  kunci:"4", pembahasan:"Keuntungan mekanik bidang miring = panjang ÷ tinggi = 8 ÷ 2 = 4."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Sebuah termometer menunjukkan suhu suatu zat 77°F. Bila dinyatakan dalam skala Celsius, suhu zat tersebut adalah ... °C.",
  kunci:"25", pembahasan:"°C = 5/9 × (°F − 32) = 5/9 × (77 − 32) = 5/9 × 45 = 25 °C."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Dua alat listrik dinyalakan bersamaan selama 2 jam (lihat tabel). Total energi listrik yang digunakan kedua alat adalah ... Wh.",
  gambar:{t:"table",caption:"Daya alat listrik",head:["Alat","Daya"],rows:[["Televisi","100 W"],["Kulkas","150 W"]]},
  kunci:"500", pembahasan:"Total daya = 250 W. Energi = 250 × 2 jam = 500 Wh."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Sebuah benda diletakkan 15 cm di depan cermin cekung yang memiliki jarak fokus 10 cm. Perbesaran bayangan yang terbentuk adalah ... kali.",
  kunci:"2", pembahasan:"1/f = 1/s + 1/s' → 1/10 − 1/15 = 1/30 → s' = 30 cm. Perbesaran M = s'/s = 30/15 = 2 kali."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Sebuah dongkrak hidrolik digunakan untuk mengangkat mobil (lihat tabel data). Gaya yang harus diberikan pada penampang kecil agar mobil terangkat adalah ... N.",
  gambar:{t:"table",caption:"Data dongkrak hidrolik",head:["Penampang","Luas","Gaya"],rows:[["Kecil","5 cm²","?"],["Besar","150 cm²","6.000 N (berat mobil)"]]},
  kunci:"200", pembahasan:"F₁ = F₂ × (A₁ ÷ A₂) = 6.000 × (5 ÷ 150) = 200 N."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan diagram komposisi gas penyusun atmosfer Bumi. Gas yang paling banyak menyusun atmosfer adalah ....",
  gambar:{t:"pie",title:"Komposisi atmosfer Bumi",slices:[{label:"Nitrogen",value:78},{label:"Oksigen",value:21},{label:"Gas lain",value:1}]},
  kunci:"nitrogen|n2", pembahasan:"Bagian terbesar diagram (78%) adalah nitrogen → gas terbanyak di atmosfer."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Perhatikan urutan tahap siklus air berikut. Setelah air laut menguap (evaporasi) lalu mengembun (kondensasi) membentuk awan, tahap selanjutnya adalah ....",
  gambar:{t:"story",emoji:"💧",text:"Evaporasi → kondensasi (awan) → ... → air mengalir kembali ke laut."},
  kunci:"presipitasi|hujan|pengendapan", pembahasan:"Setelah awan terbentuk, titik air jatuh ke Bumi sebagai hujan (presipitasi)."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Saat di Makassar (WITA) menunjukkan pukul 10.00, maka di London (GMT) saat itu menunjukkan pukul .... (WITA = GMT + 8 jam).",
  kunci:"02.00|02:00|2.00|2", pembahasan:"GMT = WITA − 8 jam = 10.00 − 8 = 02.00."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Saat Bulan purnama, posisi Matahari, Bumi, dan Bulan berada pada satu garis lurus. Akibat gaya gravitasi yang saling memperkuat, air laut mengalami pasang ....",
  kunci:"purnama|maksimum|besar|tertinggi|maksimal", pembahasan:"Saat segaris (purnama/baru), gravitasi Matahari dan Bulan searah → pasang naik tertinggi (pasang purnama)."}
]},

/* ========================= PAKET 5 ========================= */
{ id:5, nama:"Paket 5", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel bagian akar dan fungsinya. Bagian akar yang berfungsi memperluas bidang penyerapan air dan mineral adalah ....",
  gambar:{t:"table",caption:"Bagian akar",head:["Bagian","Fungsi"],rows:[["Tudung akar","Melindungi ujung akar"],["Rambut akar","Memperluas penyerapan air"],["Pangkal akar","Menyambung ke batang"]]},
  kunci:"rambut akar|bulu akar", pembahasan:"Rambut akar memperluas permukaan akar sehingga penyerapan air dan mineral lebih banyak."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan rantai makanan di ekosistem laut berikut. Organisme yang berperan sebagai produsen adalah ....",
  gambar:{t:"foodweb",nodes:[{id:"fito",label:"Fitoplankton",x:0.12,y:0.5},{id:"zoo",label:"Zooplankton",x:0.4,y:0.5},{id:"ikankecil",label:"Ikan kecil",x:0.66,y:0.5},{id:"ikanbesar",label:"Ikan besar",x:0.92,y:0.5}],links:[["fito","zoo"],["zoo","ikankecil"],["ikankecil","ikanbesar"]]},
  kunci:"fitoplankton", pembahasan:"Fitoplankton mampu berfotosintesis sehingga berperan sebagai produsen di ekosistem laut."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Pada percobaan menghitung jumlah gelembung gas Hydrilla pada berbagai intensitas cahaya, hal yang diukur dan dicatat (variabel terikat) adalah ....",
  gambar:{t:"table",caption:"Data percobaan",head:["Intensitas cahaya","Gelembung / menit"],rows:[["Rendah","5"],["Sedang","12"],["Tinggi","20"]]},
  kunci:"jumlah gelembung|laju fotosintesis|banyak gelembung|jumlah gelembung gas", pembahasan:"Yang diukur sebagai hasil percobaan adalah jumlah gelembung (menunjukkan laju fotosintesis)."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan skema jantung manusia. Bagian jantung yang memompa darah kaya oksigen ke seluruh tubuh adalah ....",
  gambar:{t:"story",emoji:"❤️",text:"Darah dari paru-paru (kaya oksigen) masuk ke serambi kiri, lalu ke bilik kiri, kemudian dipompa ke seluruh tubuh."},
  kunci:"bilik kiri|ventrikel kiri", pembahasan:"Bilik kiri (ventrikel kiri) memompa darah kaya oksigen ke seluruh tubuh melalui aorta."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel interaksi antarorganisme. Interaksi yang merupakan simbiosis komensalisme (satu untung, satu tidak terpengaruh) adalah ....",
  gambar:{t:"table",caption:"Interaksi organisme",head:["Interaksi","Organisme 1","Organisme 2"],rows:[["Anggrek – Pohon","Untung","Tidak terpengaruh"],["Kutu – Kerbau","Untung","Rugi"],["Lebah – Bunga","Untung","Untung"]]},
  kunci:"anggrek - pohon|anggrek-pohon|anggrek dan pohon|anggrek", pembahasan:"Komensalisme = satu untung, satu tidak terpengaruh → anggrek menumpang pada pohon."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Tanaman tinggi bergenotipe Tt disilangkan dengan sesamanya (Tt × Tt). Dari 400 keturunan, jumlah tanaman yang berfenotipe pendek (tt) diperkirakan ... tanaman.",
  kunci:"100", pembahasan:"Tt × Tt → tinggi : pendek = 3 : 1. Pendek = 1/4 × 400 = 100 tanaman."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Pada suatu rantai makanan, energi berpindah ke tingkat berikutnya hanya sekitar 10%. Jika produsen menyimpan 5.000 kkal, energi yang tersedia bagi konsumen tingkat II diperkirakan ... kkal.",
  gambar:{t:"bar",title:"Aliran energi (kkal)",labels:["Produsen","Konsumen I","Konsumen II"],values:[5000,500,50]},
  kunci:"50", pembahasan:"Produsen 5.000 → Konsumen I 10% = 500 → Konsumen II 10% dari 500 = 50 kkal."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Batang tanaman pacar air dicelupkan ke air berwarna (eosin). Setelah beberapa jam, jika batang dipotong melintang, warna merah tampak pada berkas pengangkut yang bertugas mengangkut air dari akar ke daun, yaitu ....",
  gambar:{t:"story",emoji:"🌷",text:"Pacar air berdiri di gelas berisi air eosin merah; setelah beberapa jam, bagian dalam batang ikut memerah."},
  kunci:"xilem|pembuluh kayu", pembahasan:"Air dan zat terlarut diangkut dari akar ke daun melalui xilem (pembuluh kayu)."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan tabel besaran dan satuan SI. Besaran yang memiliki satuan kelvin adalah ....",
  gambar:{t:"table",caption:"Besaran dan satuan SI",head:["Besaran","Satuan SI"],rows:[["Suhu","kelvin"],["Kuat arus","ampere"],["Waktu","sekon"]]},
  kunci:"suhu", pembahasan:"Berdasarkan tabel, besaran dengan satuan kelvin adalah suhu."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Panas dari api unggun terasa di tubuh seseorang yang berada di dekatnya, padahal udara di antaranya tidak ikut panas. Perpindahan kalor seperti ini disebut ....",
  gambar:{t:"story",emoji:"🔥",text:"Seseorang menghangatkan tangan di dekat api unggun; panas terasa langsung memancar ke tubuh."},
  kunci:"radiasi|pancaran", pembahasan:"Kalor berpindah tanpa zat perantara (memancar) → radiasi."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Perhatikan tuas pada gambar. Besar gaya kuasa (F) yang diperlukan agar tuas seimbang adalah ... N.",
  gambar:{t:"lever",beban:360,lb:15,lk:45,unit:"cm"},
  kunci:"120", pembahasan:"F = (beban × lengan beban) ÷ lengan kuasa = (360 × 15) ÷ 45 = 120 N."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Sebuah balok dengan berat sama diletakkan pada dua posisi (lihat tabel). Tekanan yang lebih besar terhadap lantai dialami pada posisi dengan luas alas ... (isi: besar/kecil).",
  gambar:{t:"table",caption:"Balok 100 N pada dua posisi",head:["Posisi","Luas alas","Tekanan"],rows:[["A","0,5 m²","?"],["B","0,2 m²","?"]]},
  kunci:"kecil|lebih kecil|paling kecil|alas kecil", pembahasan:"Tekanan = gaya ÷ luas. Untuk gaya sama, luas alas makin kecil menghasilkan tekanan makin besar."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Sebuah gelombang bunyi merambat di udara dengan frekuensi 200 Hz dan panjang gelombang 1,7 m. Cepat rambat bunyi di udara saat itu adalah ... m/s.",
  kunci:"340", pembahasan:"v = f × λ = 200 × 1,7 = 340 m/s."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Tiga hambatan, masing-masing 6 Ω, disusun paralel (lihat tabel). Hambatan pengganti rangkaian tersebut adalah ... Ω.",
  gambar:{t:"table",caption:"Hambatan paralel",head:["Hambatan","Nilai"],rows:[["R1","6 Ω"],["R2","6 Ω"],["R3","6 Ω"]]},
  kunci:"2", pembahasan:"1/Rp = 1/6 + 1/6 + 1/6 = 3/6 → Rp = 2 Ω."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Sebanyak 100 gram es bersuhu 0°C dilebur seluruhnya menjadi air 0°C. Jika kalor lebur es 80 kal/gram, kalor yang diperlukan untuk meleburkan es tersebut adalah ... kalori.",
  kunci:"8000", pembahasan:"Q = m × kalor lebur = 100 × 80 = 8.000 kalori."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Sebuah mobil bergerak dengan kecepatan awal 10 m/s lalu dipercepat 2 m/s² selama 5 detik. Jarak yang ditempuh mobil selama selang waktu tersebut adalah ... m.",
  kunci:"75", pembahasan:"s = v₀·t + ½·a·t² = 10×5 + ½×2×5² = 50 + 25 = 75 m."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel jumlah satelit beberapa planet. Planet yang tidak memiliki satelit alami adalah ....",
  gambar:{t:"table",caption:"Jumlah satelit planet",head:["Planet","Jumlah satelit"],rows:[["Merkurius","0"],["Bumi","1"],["Mars","2"],["Jupiter","79"]]},
  kunci:"merkurius", pembahasan:"Berdasarkan tabel, Merkurius memiliki 0 satelit → tidak punya satelit alami."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Grafik suhu rata-rata bulanan suatu daerah ditunjukkan berikut. Bulan dengan suhu udara paling rendah ditunjukkan oleh bulan ....",
  gambar:{t:"line",title:"Suhu rata-rata (°C)",labels:["Jun","Jul","Agu","Sep"],values:[26,24,23,27]},
  kunci:"agustus|agu", pembahasan:"Suhu terendah (23°C) terjadi pada bulan Agustus."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Bumi berotasi 360° dalam waktu 24 jam. Berdasarkan hal itu, setiap perbedaan bujur 15° di permukaan Bumi setara dengan perbedaan waktu ... jam.",
  kunci:"1", pembahasan:"360° ÷ 24 jam = 15° per jam, sehingga selisih 15° = 1 jam."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Saat gerhana Matahari terjadi, Bulan berada pada titik terjauh dari Bumi sehingga tidak menutupi seluruh piringan Matahari; bagian tepi Matahari masih tampak bercahaya. Jenis gerhana Matahari ini disebut gerhana Matahari ....",
  kunci:"cincin", pembahasan:"Bila Bulan tampak lebih kecil dari Matahari, tepi Matahari membentuk cincin cahaya → gerhana Matahari cincin."}
]},

/* ========================= PAKET 6 ========================= */
{ id:6, nama:"Paket 6", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel alat pernapasan beberapa hewan. Hewan yang bernapas menggunakan insang adalah ....",
  gambar:{t:"table",caption:"Alat pernapasan hewan",head:["Hewan","Alat pernapasan"],rows:[["Ikan mas","Insang"],["Burung","Paru-paru"],["Cacing","Permukaan kulit"]]},
  kunci:"ikan mas|ikan", pembahasan:"Berdasarkan tabel, hewan yang bernapas dengan insang adalah ikan mas."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel cara berkembang biak hewan. Hewan yang berkembang biak dengan cara melahirkan (vivipar) adalah ....",
  gambar:{t:"table",caption:"Cara berkembang biak",head:["Hewan","Cara"],rows:[["Ayam","Bertelur"],["Kucing","Melahirkan"],["Buaya","Bertelur"]]},
  kunci:"kucing", pembahasan:"Vivipar = berkembang biak dengan melahirkan → kucing."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel bentuk kaki burung dan tempat hidupnya. Burung dengan kaki berselaput paling sesuai hidup di lingkungan ....",
  gambar:{t:"table",caption:"Bentuk kaki burung",head:["Burung","Bentuk kaki","Ciri"],rows:[["Bebek","Berselaput","Untuk berenang"],["Elang","Bercakar tajam","Untuk mencengkeram"],["Pelatuk","Dua jari depan-belakang","Untuk memanjat"]]},
  kunci:"air|perairan|berair", pembahasan:"Kaki berselaput memudahkan berenang, cocok untuk burung yang hidup di lingkungan air."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Ketika seseorang menghembuskan napas ke permukaan cermin, cermin menjadi berembun. Hal ini menunjukkan bahwa udara yang dikeluarkan paru-paru mengandung ... yang berasal dari proses pernapasan.",
  gambar:{t:"story",emoji:"😮‍💨",text:"Napas dihembuskan ke kaca; permukaan kaca menjadi buram/berembun."},
  kunci:"uap air|air|uap", pembahasan:"Embun pada cermin menunjukkan udara pernapasan mengandung uap air (hasil ekskresi paru-paru)."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan jaring-jaring makanan berikut. Bila populasi ular menurun, organisme yang populasinya cenderung meningkat karena kehilangan pemangsa adalah ....",
  gambar:{t:"foodweb",nodes:[{id:"padi",label:"Padi",x:0.12,y:0.5},{id:"tikus",label:"Tikus",x:0.42,y:0.3},{id:"ular",label:"Ular",x:0.7,y:0.5},{id:"elang",label:"Elang",x:0.92,y:0.7}],links:[["padi","tikus"],["tikus","ular"],["ular","elang"]]},
  kunci:"tikus", pembahasan:"Ular memangsa tikus. Bila ular berkurang, tikus kehilangan pemangsa sehingga populasinya meningkat."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel jenis sendi dan contoh gerakannya. Sendi yang memungkinkan gerakan ke segala arah, seperti pada pangkal lengan, adalah sendi ....",
  gambar:{t:"table",caption:"Jenis sendi",head:["Sendi","Arah gerak","Contoh"],rows:[["Peluru","Segala arah","Bahu, pinggul"],["Engsel","Satu arah","Lutut, siku"],["Putar","Berputar","Leher"]]},
  kunci:"peluru", pembahasan:"Sendi peluru memungkinkan gerakan ke segala arah, terdapat pada bahu dan pinggul."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Bunga warna merah muda (Mm) hasil persilangan intermediet disilangkan dengan sesamanya (Mm × Mm). Dari 200 keturunan, jumlah bunga berwarna merah muda diperkirakan ... tanaman.",
  kunci:"100", pembahasan:"Mm × Mm intermediet → 1 merah : 2 merah muda : 1 putih. Merah muda = 2/4 × 200 = 100 tanaman."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Adonan roti yang diberi ragi (Saccharomyces) dibiarkan beberapa jam dan mengembang. Adonan mengembang karena ragi melakukan fermentasi yang menghasilkan gas ....",
  gambar:{t:"story",emoji:"🍞",text:"Adonan roti sebelum didiamkan kecil, setelah beberapa jam mengembang menjadi dua kali lebih besar."},
  kunci:"karbon dioksida|co2|karbondioksida", pembahasan:"Fermentasi oleh ragi menghasilkan gas karbon dioksida yang membuat adonan mengembang."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan tabel alat ukur dan besarannya. Alat yang tepat untuk mengukur suhu badan adalah ....",
  gambar:{t:"table",caption:"Alat ukur",head:["Alat","Mengukur"],rows:[["Termometer","Suhu"],["Neraca","Massa"],["Stopwatch","Waktu"]]},
  kunci:"termometer", pembahasan:"Berdasarkan tabel, alat untuk mengukur suhu adalah termometer."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Lampu-lampu di rumah dipasang sedemikian rupa sehingga bila satu lampu mati, lampu yang lain tetap menyala. Susunan rangkaian listrik seperti ini adalah rangkaian ....",
  gambar:{t:"story",emoji:"💡",text:"Beberapa lampu menyala; satu lampu dimatikan, lampu yang lain tetap menyala normal."},
  kunci:"paralel", pembahasan:"Pada rangkaian paralel, tiap cabang berdiri sendiri sehingga matinya satu lampu tidak memengaruhi yang lain."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Sebuah suhu zat tercatat 30°C. Bila dinyatakan dalam skala Fahrenheit, suhu zat tersebut adalah ... °F.",
  kunci:"86", pembahasan:"°F = (9/5 × °C) + 32 = (9/5 × 30) + 32 = 54 + 32 = 86 °F."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Sebuah katrol bergerak (keuntungan mekanik 2) digunakan untuk mengangkat beban (lihat data). Gaya kuasa yang diperlukan adalah ... N.",
  gambar:{t:"table",caption:"Data katrol",head:["Besaran","Nilai"],rows:[["Berat beban","400 N"],["Keuntungan mekanik","2"]]},
  kunci:"200", pembahasan:"F = berat ÷ keuntungan mekanik = 400 ÷ 2 = 200 N."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Saat hujan badai, kilat terlihat lalu 5 detik kemudian terdengar guntur. Bila cepat rambat bunyi 340 m/s, jarak sumber petir dari pengamat adalah ... m.",
  kunci:"1700", pembahasan:"s = v × t = 340 × 5 = 1.700 m (cahaya kilat dianggap sampai seketika)."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Sebuah pemanas air listrik berdaya 500 W dinyalakan selama 3 jam. Energi listrik yang digunakannya adalah ... Wh.",
  kunci:"1500", pembahasan:"Energi = daya × waktu = 500 × 3 = 1.500 Wh."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Sebuah pompa hidrolik memiliki luas penampang kecil 4 cm² dan penampang besar 200 cm². Jika pada penampang kecil diberi gaya 30 N, gaya angkat pada penampang besar adalah ... N.",
  gambar:{t:"table",caption:"Data pompa hidrolik",head:["Penampang","Luas","Gaya"],rows:[["Kecil","4 cm²","30 N"],["Besar","200 cm²","?"]]},
  kunci:"1500", pembahasan:"F₂ = F₁ × (A₂ ÷ A₁) = 30 × (200 ÷ 4) = 30 × 50 = 1.500 N."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Sebuah mobil melaju dengan kecepatan 72 km/jam (setara 20 m/s) lalu direm hingga berhenti dalam 4 detik. Besar perlambatan mobil tersebut adalah ... m/s².",
  kunci:"5", pembahasan:"a = (kecepatan awal − akhir) ÷ waktu = (20 − 0) ÷ 4 = 5 m/s² (perlambatan)."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel suhu permukaan beberapa planet. Berdasarkan data dan letaknya, planet yang dijuluki 'planet merah' karena permukaannya kemerahan adalah ....",
  gambar:{t:"table",caption:"Ciri planet",head:["Planet","Warna permukaan"],rows:[["Mars","Kemerahan (oksida besi)"],["Bumi","Biru kehijauan"],["Venus","Putih kekuningan"]]},
  kunci:"mars", pembahasan:"Mars berwarna kemerahan karena tanahnya mengandung oksida besi → 'planet merah'."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Grafik berikut menunjukkan suhu di dalam Bumi pada berbagai kedalaman. Berdasarkan data, semakin ke dalam Bumi, suhunya semakin ....",
  gambar:{t:"line",title:"Suhu (°C) terhadap kedalaman (km)",labels:["0","10","20","30"],values:[25,300,600,900]},
  kunci:"tinggi|naik|panas|bertambah|meningkat", pembahasan:"Data menunjukkan suhu naik seiring bertambahnya kedalaman → makin dalam makin panas."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Suatu acara disiarkan langsung pukul 19.00 WIB. Penonton di Makassar (WITA) menyaksikan acara yang sama pada pukul ... waktu setempat.",
  kunci:"20.00|20:00|20|8 malam", pembahasan:"WITA = WIB + 1 jam → 19.00 + 1 = 20.00 WITA."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Perhatikan tabel ciri beberapa planet. Planet yang memiliki cincin paling jelas yang tersusun dari bongkahan es dan debu adalah ....",
  gambar:{t:"table",caption:"Ciri planet",head:["Planet","Ciri khas"],rows:[["Saturnus","Cincin lebar dari es & debu"],["Bumi","Memiliki kehidupan"],["Mars","Permukaan kemerahan"]]},
  kunci:"saturnus", pembahasan:"Berdasarkan tabel, planet dengan cincin lebar dari es dan debu adalah Saturnus."}
]},

/* ========================= PAKET 7 ========================= */
{ id:7, nama:"Paket 7", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel organel sel tumbuhan dan fungsinya. Organel tempat berlangsungnya fotosintesis adalah ....",
  gambar:{t:"table",caption:"Organel sel tumbuhan",head:["Organel","Fungsi"],rows:[["Kloroplas","Tempat fotosintesis"],["Vakuola","Menyimpan cadangan"],["Inti sel","Mengatur kegiatan sel"]]},
  kunci:"kloroplas", pembahasan:"Berdasarkan tabel, fotosintesis berlangsung di kloroplas (mengandung klorofil)."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan daur hidup dua hewan pada tabel. Hewan yang mengalami metamorfosis sempurna ditunjukkan oleh ....",
  gambar:{t:"table",caption:"Daur hidup",head:["Hewan","Daur hidup"],rows:[["Nyamuk","telur–jentik–pupa–dewasa"],["Kecoa","telur–nimfa–dewasa"]]},
  kunci:"nyamuk", pembahasan:"Nyamuk melewati tahap pupa (telur–jentik–pupa–dewasa) → metamorfosis sempurna."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel interaksi antarorganisme. Interaksi antara tali putri dan tanaman inang termasuk simbiosis ....",
  gambar:{t:"table",caption:"Interaksi organisme",head:["Interaksi","Akibat"],rows:[["Tali putri – inang","Tali putri untung, inang rugi"],["Ikan badut – anemon","Keduanya untung"],["Paku tanduk rusa – pohon","Paku untung, pohon tak terpengaruh"]]},
  kunci:"parasitisme", pembahasan:"Tali putri untung, inang dirugikan → simbiosis parasitisme."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel organ pencernaan dan zat yang dihasilkan. Organ yang menghasilkan cairan empedu untuk mengemulsi lemak adalah ....",
  gambar:{t:"table",caption:"Organ dan getah pencernaan",head:["Organ","Menghasilkan","Fungsi"],rows:[["Hati","Empedu","Mengemulsi lemak"],["Pankreas","Lipase","Mencerna lemak"],["Lambung","Pepsin","Mencerna protein"]]},
  kunci:"hati|hepar", pembahasan:"Empedu yang mengemulsi lemak dihasilkan oleh hati."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Tabel berikut menunjukkan kecepatan penyerapan air oleh tanaman dengan jumlah rambut akar berbeda. Berdasarkan data, semakin banyak rambut akar, penyerapan air semakin ....",
  gambar:{t:"table",caption:"Penyerapan air",head:["Jumlah rambut akar","Air terserap (mL/jam)"],rows:[["Sedikit","5"],["Sedang","9"],["Banyak","15"]]},
  kunci:"banyak|cepat|besar|meningkat|bertambah", pembahasan:"Data menunjukkan makin banyak rambut akar, makin besar penyerapan air (memperluas bidang serap)."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan jaring-jaring makanan berikut. Jika populasi katak berkurang, populasi belalang dalam waktu dekat cenderung ....",
  gambar:{t:"foodweb",nodes:[{id:"daun",label:"Daun",x:0.12,y:0.5},{id:"belalang",label:"Belalang",x:0.42,y:0.5},{id:"katak",label:"Katak",x:0.68,y:0.5},{id:"ular",label:"Ular",x:0.92,y:0.5}],links:[["daun","belalang"],["belalang","katak"],["katak","ular"]]},
  kunci:"meningkat|bertambah|naik", pembahasan:"Katak pemangsa belalang; bila katak berkurang, belalang meningkat karena pemangsanya berkurang."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Tikus berbulu hitam heterozigot (Hh) disilangkan dengan tikus berbulu putih (hh). Dari 240 keturunan, jumlah tikus berbulu hitam diperkirakan ... ekor.",
  kunci:"120", pembahasan:"Hh × hh → 1 hitam (Hh) : 1 putih (hh). Hitam = 1/2 × 240 = 120 ekor."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Laju penguapan air (transpirasi) sebuah tanaman diukur pada kondisi berbeda (lihat tabel). Berdasarkan data, faktor yang paling memperlambat transpirasi adalah ....",
  gambar:{t:"table",caption:"Laju transpirasi",head:["Kondisi","Air menguap (mL/jam)"],rows:[["Panas & berangin","12"],["Panas tanpa angin","8"],["Lembap & teduh","3"]]},
  kunci:"lembap dan teduh|lembap|teduh|kelembapan tinggi|udara lembap", pembahasan:"Penguapan paling kecil (3 mL) terjadi saat lembap dan teduh → kondisi tersebut memperlambat transpirasi."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan tabel besaran dan satuan SI. Besaran yang memiliki satuan meter adalah ....",
  gambar:{t:"table",caption:"Besaran dan satuan SI",head:["Besaran","Satuan SI"],rows:[["Panjang","meter"],["Massa","kilogram"],["Suhu","kelvin"]]},
  kunci:"panjang", pembahasan:"Berdasarkan tabel, besaran dengan satuan meter adalah panjang."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan tabel hasil percobaan benda didekatkan pada magnet. Benda yang dapat ditarik magnet (bersifat magnetis) adalah ....",
  gambar:{t:"table",caption:"Uji benda dengan magnet",head:["Benda","Hasil"],rows:[["Paku besi","Tertarik"],["Plastik","Tidak tertarik"],["Karet","Tidak tertarik"]]},
  kunci:"paku besi|besi|paku", pembahasan:"Hanya paku besi yang tertarik magnet → bersifat magnetis (feromagnetik)."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Sebuah logam ditimbang dan diukur volumenya (lihat tabel). Massa jenis logam tersebut adalah ... g/cm³.",
  gambar:{t:"table",caption:"Data logam",head:["Besaran","Nilai"],rows:[["Massa","540 g"],["Volume","200 cm³"]]},
  kunci:"2,7|2.7", pembahasan:"Massa jenis = massa ÷ volume = 540 ÷ 200 = 2,7 g/cm³."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Perhatikan tuas pada gambar. Besar gaya kuasa (F) agar tuas seimbang adalah ... N.",
  gambar:{t:"lever",beban:600,lb:20,lk:80,unit:"cm"},
  kunci:"150", pembahasan:"F = (beban × lengan beban) ÷ lengan kuasa = (600 × 20) ÷ 80 = 150 N."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Sebuah gelombang pada tali memiliki data seperti pada tabel. Cepat rambat gelombang tersebut adalah ... m/s.",
  gambar:{t:"table",caption:"Data gelombang",head:["Besaran","Nilai"],rows:[["Frekuensi","5 Hz"],["Panjang gelombang","4 m"]]},
  kunci:"20", pembahasan:"v = f × λ = 5 × 4 = 20 m/s."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Sebuah hambatan dialiri arus listrik (lihat tabel). Beda potensial pada ujung-ujung hambatan tersebut adalah ... volt.",
  gambar:{t:"table",caption:"Data hambatan",head:["Besaran","Nilai"],rows:[["Hambatan","8 Ω"],["Kuat arus","3 A"]]},
  kunci:"24", pembahasan:"V = I × R = 3 × 8 = 24 volt."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Dua wadah air dicampur (lihat tabel) dan tidak ada kalor yang hilang ke lingkungan. Suhu campuran setelah setimbang adalah ... °C.",
  gambar:{t:"table",caption:"Pencampuran air bermassa sama",head:["Air","Massa","Suhu"],rows:[["A","100 g","80 °C"],["B","100 g","20 °C"]]},
  kunci:"50", pembahasan:"Karena massa sama, suhu campuran = (80 + 20) ÷ 2 = 50 °C."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Sebuah benda diletakkan 30 cm di depan lensa cembung yang berjarak fokus 10 cm. Jarak bayangan yang terbentuk adalah ... cm.",
  kunci:"15", pembahasan:"1/f = 1/s + 1/s' → 1/10 − 1/30 = 2/30 → s' = 15 cm."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel benda langit. Benda langit yang menjadi pusat tata surya dan memancarkan cahaya sendiri adalah ....",
  gambar:{t:"table",caption:"Benda langit",head:["Benda","Cahaya"],rows:[["Matahari","Memancarkan sendiri"],["Bulan","Memantulkan cahaya"],["Bumi","Memantulkan cahaya"]]},
  kunci:"matahari", pembahasan:"Matahari adalah bintang yang memancarkan cahaya sendiri dan menjadi pusat tata surya."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Grafik berikut menunjukkan suhu Bumi pada berbagai kedalaman. Berdasarkan data, dapat disimpulkan bahwa makin dalam menuju inti Bumi, suhunya makin ....",
  gambar:{t:"line",title:"Suhu (°C) terhadap kedalaman (km)",labels:["0","15","30","45"],values:[20,400,800,1200]},
  kunci:"tinggi|naik|panas|bertambah|meningkat", pembahasan:"Data memperlihatkan suhu naik seiring kedalaman → bagian dalam Bumi sangat panas."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Perhatikan tabel letak lintang beberapa wilayah. Wilayah yang beriklim tropis (terletak di sekitar garis khatulistiwa) adalah ....",
  gambar:{t:"table",caption:"Letak lintang wilayah",head:["Wilayah","Lintang"],rows:[["Wilayah A","2° LU"],["Wilayah B","45° LU"],["Wilayah C","60° LS"]]},
  kunci:"wilayah a|a", pembahasan:"Iklim tropis berada di sekitar khatulistiwa (lintang rendah, ±23,5°) → Wilayah A (2° LU)."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Sebuah pertandingan disiarkan langsung pukul 21.00 WIB. Seorang penonton di Jayapura (WIT) menyaksikannya pada pukul ... waktu setempat.",
  kunci:"23.00|23:00|23|11 malam", pembahasan:"WIT = WIB + 2 jam → 21.00 + 2 = 23.00 WIT."}
]},

/* ========================= PAKET 8 ========================= */
{ id:8, nama:"Paket 8", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel kelengkapan bagian bunga. Bunga yang memiliki benang sari sekaligus putik disebut bunga ....",
  gambar:{t:"table",caption:"Bagian bunga",head:["Bunga","Benang sari","Putik"],rows:[["Bunga X","Ada","Ada"],["Bunga Y","Ada","Tidak ada"],["Bunga Z","Tidak ada","Ada"]]},
  kunci:"sempurna", pembahasan:"Bunga X memiliki benang sari dan putik sekaligus → bunga sempurna."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel cara memperoleh makanan. Organisme yang dapat membuat makanannya sendiri (autotrof) adalah ....",
  gambar:{t:"table",caption:"Cara memperoleh makanan",head:["Organisme","Cara"],rows:[["Tumbuhan hijau","Membuat sendiri (fotosintesis)"],["Jamur","Menyerap dari sisa organisme"],["Sapi","Memakan tumbuhan"]]},
  kunci:"tumbuhan hijau|tumbuhan", pembahasan:"Tumbuhan hijau membuat makanan sendiri melalui fotosintesis → autotrof."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Bakteri Rhizobium hidup pada bintil akar tanaman kacang. Bakteri mengikat nitrogen yang menyuburkan tanah, sementara bakteri memperoleh tempat hidup dan makanan. Hubungan keduanya termasuk simbiosis ....",
  gambar:{t:"story",emoji:"🌱",text:"Pada akar tanaman kacang terdapat bintil-bintil tempat bakteri Rhizobium hidup."},
  kunci:"mutualisme", pembahasan:"Keduanya saling diuntungkan (tanaman subur, bakteri mendapat tempat & makanan) → mutualisme."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Seorang siswa sering duduk membungkuk ke satu sisi. Lama-kelamaan tulang belakangnya membengkok ke samping. Kelainan tulang belakang yang dialami siswa tersebut disebut ....",
  gambar:{t:"story",emoji:"🪑",text:"Posisi duduk miring/condong ke satu sisi dilakukan dalam waktu lama setiap hari."},
  kunci:"skoliosis", pembahasan:"Pembengkokan tulang belakang ke arah samping disebut skoliosis."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel komponen darah dan fungsinya. Komponen darah yang berfungsi mengangkut oksigen ke seluruh tubuh adalah ....",
  gambar:{t:"table",caption:"Komponen darah",head:["Komponen","Fungsi"],rows:[["Sel darah merah","Mengangkut oksigen"],["Sel darah putih","Melawan kuman"],["Keping darah","Membekukan darah"]]},
  kunci:"sel darah merah|eritrosit", pembahasan:"Sel darah merah (eritrosit) mengandung hemoglobin yang mengangkut oksigen."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel ciri hewan. Berdasarkan ciri-cirinya, hewan yang termasuk kelompok burung (Aves) adalah ....",
  gambar:{t:"table",caption:"Ciri hewan",head:["Hewan","Penutup tubuh","Alat gerak"],rows:[["P","Bulu","Sayap & kaki"],["Q","Sisik","Sirip"],["R","Rambut","Kaki"]]},
  kunci:"P", pembahasan:"Ciri Aves adalah tubuh berbulu dan memiliki sayap → hewan P."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Dua tanaman bunga merah heterozigot (Mm, merah dominan terhadap putih) disilangkan. Dari 200 biji yang tumbuh, jumlah tanaman yang berbunga merah diperkirakan ... tanaman.",
  kunci:"150", pembahasan:"Mm × Mm → merah : putih = 3 : 1. Merah = 3/4 × 200 = 150 tanaman."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Pada percobaan Sachs, sebagian daun ditutup kertas timah, dijemur, lalu diuji iodium. Bagian daun yang tertutup TIDAK berubah menjadi biru kehitaman. Hal ini membuktikan bahwa fotosintesis memerlukan ....",
  gambar:{t:"story",emoji:"🍃",text:"Sebagian daun ditutup rapat kertas timah; setelah diuji iodium, hanya bagian terbuka yang berwarna biru kehitaman."},
  kunci:"cahaya|cahaya matahari|sinar matahari", pembahasan:"Bagian tertutup tidak menghasilkan amilum karena tidak terkena cahaya → fotosintesis memerlukan cahaya."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Grafik berikut menunjukkan suhu air yang dipanaskan terhadap waktu. Berdasarkan grafik, air mendidih pada suhu ... °C.",
  gambar:{t:"line",title:"Suhu (°C) terhadap waktu (menit)",labels:["0","2","4","6","8"],values:[30,60,90,100,100]},
  kunci:"100", pembahasan:"Suhu tetap di 100°C meski terus dipanaskan → titik didih air = 100°C."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Sebuah bayangan dapat ditangkap pada layar saat cahaya melewati lensa. Bayangan yang dapat ditangkap layar disebut bayangan ....",
  gambar:{t:"story",emoji:"🎞️",text:"Cahaya dari proyektor melewati lensa dan membentuk gambar tajam pada layar putih."},
  kunci:"nyata|sejati|riil", pembahasan:"Bayangan yang dapat ditangkap layar adalah bayangan nyata (sejati)."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Grafik jarak terhadap waktu sebuah sepeda ditunjukkan berikut. Kecepatan rata-rata sepeda tersebut adalah ... m/s.",
  gambar:{t:"line",title:"Jarak (m) terhadap waktu (s)",labels:["0","10","20","30"],values:[0,50,100,150]},
  kunci:"5", pembahasan:"Kecepatan = 150 m ÷ 30 s = 5 m/s."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Perhatikan bidang miring pada gambar. Keuntungan mekanik bidang miring tersebut adalah ....",
  gambar:{t:"incline",panjang:6,tinggi:2,unit:"m"},
  kunci:"3", pembahasan:"Keuntungan mekanik = panjang ÷ tinggi = 6 ÷ 2 = 3."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Untuk menaikkan suhu 500 gram air sebesar 20°C diperlukan kalor sebanyak ... kalori (kalor jenis air = 1 kal/g°C).",
  kunci:"10000", pembahasan:"Q = m × c × ΔT = 500 × 1 × 20 = 10.000 kalori."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Sebuah alat listrik berdaya 200 W dinyalakan selama 60 detik. Energi listrik yang digunakannya adalah ... joule.",
  kunci:"12000", pembahasan:"Energi = daya × waktu = 200 × 60 = 12.000 joule."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Sebuah bak berisi air setinggi 1,5 m (lihat data). Tekanan hidrostatis pada dasar bak adalah ... Pa.",
  gambar:{t:"table",caption:"Data bak air",head:["Besaran","Nilai"],rows:[["Tinggi air","1,5 m"],["Massa jenis air","1.000 kg/m³"],["Gravitasi","10 m/s²"]]},
  kunci:"15000", pembahasan:"P = ρ × g × h = 1.000 × 10 × 1,5 = 15.000 Pa."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Dua lampu identik berhambatan 5 Ω disusun seri lalu dihubungkan dengan baterai 20 V. Kuat arus yang mengalir dalam rangkaian adalah ... A.",
  gambar:{t:"table",caption:"Data rangkaian seri",head:["Komponen","Nilai"],rows:[["Lampu 1","5 Ω"],["Lampu 2","5 Ω"],["Baterai","20 V"]]},
  kunci:"2", pembahasan:"R total = 5 + 5 = 10 Ω. I = V ÷ R = 20 ÷ 10 = 2 A."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel kondisi beberapa planet. Berdasarkan data, planet yang memiliki air dan dihuni makhluk hidup adalah ....",
  gambar:{t:"table",caption:"Kondisi planet",head:["Planet","Air","Kehidupan"],rows:[["Bumi","Ada","Ada"],["Mars","Sedikit (beku)","Belum ditemukan"],["Venus","Tidak ada","Tidak ada"]]},
  kunci:"bumi", pembahasan:"Berdasarkan tabel, hanya Bumi yang memiliki air melimpah dan dihuni makhluk hidup."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Grafik curah hujan suatu daerah ditunjukkan berikut. Bulan dengan curah hujan tertinggi (paling basah) adalah bulan ....",
  gambar:{t:"bar",title:"Curah hujan (mm)",labels:["Sep","Okt","Nov","Des"],values:[40,90,160,250]},
  kunci:"desember|des", pembahasan:"Curah hujan tertinggi (250 mm) terjadi pada bulan Desember → paling basah."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Perhatikan diagram posisi Bulan terhadap Bumi dan Matahari. Saat sisi Bulan yang menghadap Bumi sama sekali tidak terkena cahaya Matahari, Bulan tidak tampak dari Bumi. Fase Bulan ini disebut fase ....",
  gambar:{t:"story",emoji:"🌑",text:"Bulan berada di antara Matahari dan Bumi; sisi gelap Bulan menghadap ke Bumi."},
  kunci:"baru|bulan baru|mati|bulan mati", pembahasan:"Saat sisi gelap Bulan menghadap Bumi, Bulan tidak terlihat → fase bulan baru (bulan mati)."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Perhatikan tabel ciri khas beberapa planet. Planet yang dikenal memiliki sistem cincin paling jelas adalah ....",
  gambar:{t:"table",caption:"Ciri khas planet",head:["Planet","Ciri"],rows:[["Saturnus","Cincin lebar dan jelas"],["Jupiter","Planet terbesar"],["Neptunus","Berwarna biru, paling jauh"]]},
  kunci:"saturnus", pembahasan:"Berdasarkan tabel, planet dengan sistem cincin paling jelas adalah Saturnus."}
]},

/* ========================= PAKET 9 ========================= */
{ id:9, nama:"Paket 9", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel bagian tumbuhan dan fungsinya. Bagian tumbuhan yang berfungsi menyerap air dan zat hara dari dalam tanah adalah ....",
  gambar:{t:"table",caption:"Bagian tumbuhan",head:["Bagian","Fungsi"],rows:[["Akar","Menyerap air & zat hara"],["Daun","Tempat fotosintesis"],["Batang","Mengangkut & menopang"]]},
  kunci:"akar", pembahasan:"Berdasarkan tabel, bagian yang menyerap air dan zat hara dari tanah adalah akar."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel ciri hewan. Hewan yang termasuk kelompok mamalia (melahirkan dan menyusui) ditunjukkan oleh ....",
  gambar:{t:"table",caption:"Ciri hewan",head:["Hewan","Berkembang biak","Memberi susu"],rows:[["Lumba-lumba","Melahirkan","Ya"],["Penyu","Bertelur","Tidak"],["Hiu","Bertelur/melahirkan","Tidak"]]},
  kunci:"lumba-lumba|lumba lumba", pembahasan:"Lumba-lumba melahirkan dan menyusui anaknya → termasuk mamalia."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Jamur penyebab panu tumbuh di kulit manusia dan memperoleh makanan dari sel kulit sehingga manusia dirugikan (gatal dan bercak). Hubungan jamur panu dengan manusia termasuk simbiosis ....",
  gambar:{t:"story",emoji:"🔬",text:"Jamur menempel dan berkembang biak pada permukaan kulit, menimbulkan bercak putih yang gatal."},
  kunci:"parasitisme", pembahasan:"Jamur untung, manusia dirugikan → simbiosis parasitisme."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Saat menarik napas, otot diafragma berkontraksi sehingga rongga dada membesar dan tekanan udara di paru-paru mengecil. Akibatnya udara dari luar masuk ke paru-paru. Proses masuknya udara ini disebut ....",
  gambar:{t:"story",emoji:"🫁",text:"Diafragma turun, rongga dada membesar, udara mengalir masuk ke paru-paru."},
  kunci:"inspirasi|menghirup|inhalasi", pembahasan:"Pemasukan udara ke paru-paru karena tekanan mengecil disebut inspirasi (menghirup)."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel ciri tumbuhan dikotil dan monokotil. Tumbuhan yang memiliki akar tunggang adalah kelompok tumbuhan ....",
  gambar:{t:"table",caption:"Ciri tumbuhan",head:["Ciri","Dikotil","Monokotil"],rows:[["Akar","Tunggang","Serabut"],["Tulang daun","Menjari/menyirip","Sejajar"],["Keping biji","Dua","Satu"]]},
  kunci:"dikotil", pembahasan:"Berdasarkan tabel, akar tunggang dimiliki tumbuhan dikotil."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan jaring-jaring makanan berikut. Organisme yang berperan menguraikan sisa makhluk hidup yang mati menjadi zat hara adalah ....",
  gambar:{t:"foodweb",nodes:[{id:"rumput",label:"Rumput",x:0.12,y:0.4},{id:"belalang",label:"Belalang",x:0.42,y:0.22},{id:"katak",label:"Katak",x:0.7,y:0.4},{id:"pengurai",label:"Pengurai",x:0.42,y:0.82}],links:[["rumput","belalang"],["belalang","katak"],["katak","pengurai"],["rumput","pengurai"]]},
  kunci:"pengurai|dekomposer|perombak", pembahasan:"Organisme yang menguraikan sisa makhluk hidup mati menjadi zat hara adalah pengurai (dekomposer)."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Dua tanaman bergenotipe BbKk disilangkan (BbKk × BbKk) dengan kedua sifat dominan penuh. Banyaknya macam fenotipe yang muncul pada keturunannya adalah ... macam.",
  kunci:"4", pembahasan:"Persilangan dihibrid dominan penuh menghasilkan perbandingan 9 : 3 : 3 : 1 → 4 macam fenotipe."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Sebatang tanaman dicelupkan ke air berwarna; setelah beberapa jam batangnya ikut berwarna pada bagian pembuluh tertentu. Pembuluh yang mengangkut air dan mineral dari akar ke daun tersebut adalah ....",
  gambar:{t:"story",emoji:"🌿",text:"Air berwarna naik dari akar; potongan melintang batang menunjukkan warna pada berkas pengangkut bagian dalam."},
  kunci:"xilem|pembuluh kayu", pembahasan:"Air dan mineral diangkut dari akar ke daun melalui xilem (pembuluh kayu)."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan tabel besaran dan satuannya. Besaran yang memiliki satuan sekon (detik) adalah ....",
  gambar:{t:"table",caption:"Besaran dan satuan SI",head:["Besaran","Satuan SI"],rows:[["Waktu","sekon"],["Panjang","meter"],["Massa","kilogram"]]},
  kunci:"waktu", pembahasan:"Berdasarkan tabel, besaran dengan satuan sekon adalah waktu."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Sebuah besi dililiti kawat yang dialiri arus listrik searah sehingga besi menjadi bersifat magnet. Cara membuat magnet seperti ini disebut cara ....",
  gambar:{t:"story",emoji:"🔌",text:"Paku besi dililiti kawat yang ujung-ujungnya dihubungkan ke baterai; paku dapat menarik jarum."},
  kunci:"elektromagnetik|elektromagnet|mengalirkan arus listrik|dialiri arus listrik|induksi listrik", pembahasan:"Membuat magnet menggunakan arus listrik (besi dililiti kawat berarus) disebut cara elektromagnetik."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Pada sebuah benda bekerja dua gaya berlawanan arah seperti gambar. Resultan gaya yang bekerja pada benda adalah ... N.",
  gambar:{t:"story",emoji:"➡️",text:"Gaya 80 N menarik ke kanan, gaya 30 N menarik ke kiri pada benda yang sama."},
  kunci:"50", pembahasan:"Gaya berlawanan arah dikurangkan: 80 − 30 = 50 N (ke kanan)."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Perhatikan tuas pada gambar. Besar gaya kuasa (F) agar tuas seimbang adalah ... N.",
  gambar:{t:"lever",beban:300,lb:20,lk:60,unit:"cm"},
  kunci:"100", pembahasan:"F = (beban × lengan beban) ÷ lengan kuasa = (300 × 20) ÷ 60 = 100 N."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Sebuah benda bergetar dengan frekuensi 50 Hz. Periode getaran benda tersebut adalah ... detik.",
  kunci:"0,02|0.02", pembahasan:"Periode = 1 ÷ frekuensi = 1 ÷ 50 = 0,02 detik."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Sebuah lampu dengan data seperti pada tabel dipasang pada sumber listrik. Kuat arus yang mengalir pada lampu adalah ... A.",
  gambar:{t:"table",caption:"Data lampu",head:["Besaran","Nilai"],rows:[["Tegangan","220 V"],["Hambatan","220 Ω"]]},
  kunci:"1", pembahasan:"I = V ÷ R = 220 ÷ 220 = 1 A."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Suhu kulit tangan diukur sebelum dan sesudah ditetesi cairan (lihat tabel). Kulit yang ditetesi alkohol terasa lebih dingin dibanding yang ditetesi air karena alkohol lebih cepat ....",
  gambar:{t:"table",caption:"Suhu kulit (°C)",head:["Cairan","Sebelum","Sesudah"],rows:[["Air","32","31"],["Alkohol","32","27"]]},
  kunci:"menguap|menguap (evaporasi)|berubah menjadi gas|menyerap kalor", pembahasan:"Alkohol lebih mudah menguap; penguapan menyerap kalor dari kulit sehingga kulit terasa lebih dingin."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Empat benda diukur massa jenisnya (lihat tabel). Massa jenis air 1,0 g/cm³. Benda yang akan terapung jika dimasukkan ke dalam air adalah ....",
  gambar:{t:"table",caption:"Massa jenis benda",head:["Benda","Massa jenis (g/cm³)"],rows:[["K","2,5"],["L","0,8"],["M","1,2"],["N","7,8"]]},
  kunci:"L", pembahasan:"Benda terapung jika massa jenisnya lebih kecil dari air (1,0). Hanya benda L (0,8 g/cm³) yang terapung."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel letak beberapa benda langit. Benda langit kecil yang banyak terdapat di antara orbit Mars dan Jupiter disebut ....",
  gambar:{t:"table",caption:"Benda langit",head:["Benda","Letak"],rows:[["Asteroid","Antara orbit Mars dan Jupiter"],["Komet","Orbit sangat lonjong"],["Satelit","Mengelilingi planet"]]},
  kunci:"asteroid", pembahasan:"Berdasarkan tabel, benda kecil di antara orbit Mars dan Jupiter adalah asteroid."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Pelangi muncul setelah hujan ketika cahaya Matahari mengenai titik-titik air di udara, lalu terurai menjadi berbagai warna. Peristiwa penguraian cahaya putih menjadi banyak warna ini disebut ....",
  gambar:{t:"story",emoji:"🌈",text:"Cahaya Matahari melewati titik-titik air hujan dan terurai menjadi tujuh warna pelangi."},
  kunci:"dispersi|penguraian cahaya|dispersi cahaya|pembiasan", pembahasan:"Penguraian cahaya putih menjadi spektrum warna disebut dispersi cahaya (akibat pembiasan)."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Akibat Bumi berputar pada porosnya, suatu wilayah mengalami siang dan malam secara bergantian, serta terjadi perbedaan ... antarwilayah yang berbeda bujurnya.",
  gambar:{t:"story",emoji:"🌍",text:"Bumi berputar pada porosnya dari barat ke timur; bagian yang menghadap Matahari mengalami siang."},
  kunci:"waktu", pembahasan:"Rotasi Bumi menyebabkan pergantian siang-malam dan perbedaan waktu antarwilayah."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Perhatikan tabel susunan lapisan Bumi. Inti dalam Bumi yang berbentuk padat terutama tersusun atas logam besi dan ....",
  gambar:{t:"table",caption:"Lapisan Bumi",head:["Lapisan","Penyusun utama"],rows:[["Kerak","Batuan"],["Mantel","Magma kental"],["Inti dalam","Besi dan nikel (padat)"]]},
  kunci:"nikel", pembahasan:"Berdasarkan tabel, inti dalam Bumi tersusun atas besi dan nikel."}
]},

/* ========================= PAKET 10 ========================= */
{ id:10, nama:"Paket 10", soal:[
 {no:1, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel jenis makanan beberapa hewan. Hewan yang termasuk pemakan segala (omnivora) adalah ....",
  gambar:{t:"table",caption:"Jenis makanan hewan",head:["Hewan","Makanan"],rows:[["Sapi","Rumput"],["Harimau","Daging"],["Ayam","Biji-bijian & cacing"]]},
  kunci:"ayam", pembahasan:"Ayam memakan tumbuhan (biji) dan hewan (cacing) → omnivora (pemakan segala)."},
 {no:2, ranah:"Biologi", level:"mudah",
  soal:"Perhatikan tabel cara perkembangbiakan tumbuhan. Cara perkembangbiakan vegetatif buatan yang dilakukan dengan bantuan manusia ditunjukkan oleh ....",
  gambar:{t:"table",caption:"Perkembangbiakan tumbuhan",head:["Cara","Jenis"],rows:[["Mencangkok","Vegetatif buatan"],["Biji","Generatif"],["Tunas","Vegetatif alami"]]},
  kunci:"mencangkok|cangkok", pembahasan:"Mencangkok adalah perkembangbiakan vegetatif buatan (dengan bantuan manusia)."},
 {no:3, ranah:"Biologi", level:"sedang",
  soal:"Burung jalak memakan kutu yang ada di punggung kerbau. Jalak memperoleh makanan, sedangkan kerbau terbebas dari kutu yang mengganggu. Hubungan keduanya termasuk simbiosis ....",
  gambar:{t:"story",emoji:"🐃",text:"Burung jalak hinggap di punggung kerbau dan mematuki kutu-kutu yang menempel di sana."},
  kunci:"mutualisme", pembahasan:"Keduanya diuntungkan (jalak makan, kerbau bebas kutu) → mutualisme."},
 {no:4, ranah:"Biologi", level:"sedang",
  soal:"Hasil pemeriksaan darah tiga pasien ditunjukkan tabel (kadar hemoglobin normal 12–16 g/dL). Pasien yang kemungkinan menderita anemia (kekurangan hemoglobin) adalah ....",
  gambar:{t:"table",caption:"Kadar hemoglobin",head:["Pasien","Hemoglobin (g/dL)"],rows:[["Pasien A","14"],["Pasien B","8"],["Pasien C","13"]]},
  kunci:"pasien b|b", pembahasan:"Kadar hemoglobin Pasien B (8 g/dL) di bawah normal → menderita anemia."},
 {no:5, ranah:"Biologi", level:"sedang",
  soal:"Perhatikan tabel bagian daun dan fungsinya. Bagian yang berperan sebagai tempat pertukaran gas (oksigen dan karbon dioksida) pada daun adalah ....",
  gambar:{t:"table",caption:"Bagian daun",head:["Bagian","Fungsi"],rows:[["Stomata","Pertukaran gas & penguapan"],["Klorofil","Menyerap cahaya"],["Tulang daun","Mengangkut zat"]]},
  kunci:"stomata|mulut daun", pembahasan:"Stomata (mulut daun) menjadi tempat pertukaran gas dan penguapan air."},
 {no:6, ranah:"Biologi", level:"sedang",
  soal:"Grafik berikut menunjukkan jumlah organisme tiap tingkat dalam suatu piramida makanan. Kelompok organisme yang menempati dasar piramida (jumlah terbanyak) adalah ....",
  gambar:{t:"bar",title:"Jumlah organisme",labels:["Produsen","Konsumen I","Konsumen II"],values:[1000,150,20]},
  kunci:"produsen", pembahasan:"Produsen memiliki jumlah terbanyak (1000) sehingga menempati dasar piramida makanan."},
 {no:7, ranah:"Biologi", level:"sulit",
  soal:"Tanaman bergenotipe AaBb diuji silang dengan tanaman bergenotipe aabb (AaBb × aabb). Banyaknya macam fenotipe keturunan yang dihasilkan adalah ... macam.",
  kunci:"4", pembahasan:"Uji silang AaBb × aabb menghasilkan AaBb, Aabb, aaBb, aabb → 4 macam fenotipe."},
 {no:8, ranah:"Biologi", level:"sulit",
  soal:"Perhatikan tabel bagian sistem saraf pusat dan fungsinya. Bagian yang mengatur kegiatan tak sadar seperti denyut jantung dan gerak pernapasan adalah ....",
  gambar:{t:"table",caption:"Sistem saraf pusat",head:["Bagian","Fungsi"],rows:[["Otak besar","Berpikir & gerak sadar"],["Otak kecil","Keseimbangan & koordinasi"],["Sumsum lanjutan","Denyut jantung & pernapasan"]]},
  kunci:"sumsum lanjutan|medula oblongata|medula oblongata (sumsum lanjutan)", pembahasan:"Sumsum lanjutan (medula oblongata) mengatur denyut jantung dan pernapasan (kegiatan tak sadar)."},
 {no:9, ranah:"Fisika", level:"mudah",
  soal:"Perhatikan tabel alat ukur panjang. Alat yang paling tepat untuk mengukur diameter kelereng secara teliti adalah ....",
  gambar:{t:"table",caption:"Alat ukur panjang",head:["Alat","Kegunaan"],rows:[["Mistar","Panjang benda lurus"],["Jangka sorong","Diameter benda kecil (teliti)"],["Meteran pita","Jarak panjang"]]},
  kunci:"jangka sorong", pembahasan:"Diameter kelereng diukur teliti menggunakan jangka sorong."},
 {no:10, ranah:"Fisika", level:"mudah",
  soal:"Saat air dipanaskan dalam panci, air bagian bawah yang panas naik dan air bagian atas yang dingin turun sehingga panas merata. Perpindahan kalor yang disertai perpindahan zatnya ini disebut ....",
  gambar:{t:"story",emoji:"🍲",text:"Air dalam panci dipanaskan; terlihat aliran air panas naik dari dasar dan air dingin turun dari atas."},
  kunci:"konveksi|aliran", pembahasan:"Perpindahan kalor pada zat cair/gas yang disertai aliran zat disebut konveksi."},
 {no:11, ranah:"Fisika", level:"sedang",
  soal:"Sebuah mobil melaju dengan kecepatan 36 km/jam. Jika dinyatakan dalam satuan m/s, kecepatan mobil tersebut adalah ... m/s.",
  kunci:"10", pembahasan:"36 km/jam = (36 × 1.000) ÷ 3.600 = 10 m/s."},
 {no:12, ranah:"Fisika", level:"sedang",
  soal:"Sebuah sistem katrol majemuk memiliki data seperti pada tabel. Gaya kuasa minimal untuk mengangkat beban tersebut adalah ... N.",
  gambar:{t:"table",caption:"Data katrol majemuk",head:["Besaran","Nilai"],rows:[["Berat beban","800 N"],["Jumlah tali penyangga","4"]]},
  kunci:"200", pembahasan:"Keuntungan mekanik = jumlah tali = 4. F = berat ÷ 4 = 800 ÷ 4 = 200 N."},
 {no:13, ranah:"Fisika", level:"sedang",
  soal:"Dalam waktu 2 detik terbentuk 10 gelombang pada permukaan air. Frekuensi gelombang tersebut adalah ... Hz.",
  kunci:"5", pembahasan:"Frekuensi = jumlah gelombang ÷ waktu = 10 ÷ 2 = 5 Hz."},
 {no:14, ranah:"Fisika", level:"sedang",
  soal:"Sebuah lampu dipasang pada tegangan 220 V dan dialiri arus 0,2 A. Daya lampu tersebut adalah ... watt.",
  kunci:"44", pembahasan:"Daya = V × I = 220 × 0,2 = 44 watt."},
 {no:15, ranah:"Fisika", level:"sulit",
  soal:"Sebuah kotak memiliki data seperti pada tabel. Tekanan yang diberikan kotak pada lantai adalah ... Pa.",
  gambar:{t:"table",caption:"Data kotak",head:["Besaran","Nilai"],rows:[["Berat kotak","60 N"],["Luas alas","0,02 m² (20 cm × 10 cm)"]]},
  kunci:"3000", pembahasan:"P = gaya ÷ luas = 60 ÷ 0,02 = 3.000 Pa."},
 {no:16, ranah:"Fisika", level:"sulit",
  soal:"Sebuah benda bergerak dari keadaan diam dengan percepatan tetap 2 m/s² selama 5 detik. Jarak yang ditempuh benda tersebut adalah ... m.",
  kunci:"25", pembahasan:"s = ½ × a × t² = ½ × 2 × 5² = ½ × 2 × 25 = 25 m."},
 {no:17, ranah:"IPBA", level:"mudah",
  soal:"Perhatikan tabel urutan planet dari Matahari. Planet yang menempati urutan kedua dari Matahari adalah ....",
  gambar:{t:"table",caption:"Urutan planet",head:["Urutan","Planet"],rows:[["1","Merkurius"],["2","Venus"],["3","Bumi"],["4","Mars"]]},
  kunci:"venus", pembahasan:"Berdasarkan tabel, planet urutan kedua dari Matahari adalah Venus."},
 {no:18, ranah:"IPBA", level:"sedang",
  soal:"Suatu daerah sering mengalami getaran permukaan Bumi akibat pergerakan/pergeseran lempeng Bumi di bawahnya. Jenis gempa yang terjadi di daerah tersebut adalah gempa ....",
  gambar:{t:"story",emoji:"🌋",text:"Dua lempeng Bumi saling bergesekan dan bergeser, menimbulkan getaran kuat di permukaan."},
  kunci:"tektonik", pembahasan:"Gempa akibat pergerakan/pergeseran lempeng Bumi disebut gempa tektonik."},
 {no:19, ranah:"IPBA", level:"sedang",
  soal:"Perhatikan diagram kedudukan Bumi terhadap Matahari pada tanggal 21 Juni. Belahan Bumi utara lebih condong ke arah Matahari sehingga belahan Bumi utara mengalami musim ....",
  gambar:{t:"story",emoji:"☀️",text:"Pada 21 Juni, sumbu Bumi membuat belahan utara lebih dekat menghadap Matahari sehingga menerima sinar lebih banyak."},
  kunci:"panas|musim panas", pembahasan:"Belahan Bumi yang condong ke Matahari menerima sinar lebih banyak → mengalami musim panas."},
 {no:20, ranah:"IPBA", level:"sulit",
  soal:"Akibat Bulan berevolusi mengelilingi Bumi, kedudukan Bulan terhadap Matahari dan Bumi berubah-ubah sehingga bentuk Bulan yang terlihat dari Bumi (sabit, separuh, purnama) ikut berubah. Perubahan kenampakan bentuk Bulan ini disebut ... Bulan.",
  kunci:"fase|fase-fase|fase bulan", pembahasan:"Perubahan kenampakan bentuk Bulan akibat revolusinya disebut fase-fase Bulan."}
]}

];
